package com.webank.webase.chain.mgr.repository.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbFrontExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    protected long start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    protected long count = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public TbFrontExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public void setStart(long start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public long getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public void setCount(long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public long getCount() {
        return count;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFrontIdIsNull() {
            addCriterion("front_id is null");
            return (Criteria) this;
        }

        public Criteria andFrontIdIsNotNull() {
            addCriterion("front_id is not null");
            return (Criteria) this;
        }

        public Criteria andFrontIdEqualTo(Integer value) {
            addCriterion("front_id =", value, "frontId");
            return (Criteria) this;
        }

        public Criteria andFrontIdNotEqualTo(Integer value) {
            addCriterion("front_id <>", value, "frontId");
            return (Criteria) this;
        }

        public Criteria andFrontIdGreaterThan(Integer value) {
            addCriterion("front_id >", value, "frontId");
            return (Criteria) this;
        }

        public Criteria andFrontIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("front_id >=", value, "frontId");
            return (Criteria) this;
        }

        public Criteria andFrontIdLessThan(Integer value) {
            addCriterion("front_id <", value, "frontId");
            return (Criteria) this;
        }

        public Criteria andFrontIdLessThanOrEqualTo(Integer value) {
            addCriterion("front_id <=", value, "frontId");
            return (Criteria) this;
        }

        public Criteria andFrontIdIn(List<Integer> values) {
            addCriterion("front_id in", values, "frontId");
            return (Criteria) this;
        }

        public Criteria andFrontIdNotIn(List<Integer> values) {
            addCriterion("front_id not in", values, "frontId");
            return (Criteria) this;
        }

        public Criteria andFrontIdBetween(Integer value1, Integer value2) {
            addCriterion("front_id between", value1, value2, "frontId");
            return (Criteria) this;
        }

        public Criteria andFrontIdNotBetween(Integer value1, Integer value2) {
            addCriterion("front_id not between", value1, value2, "frontId");
            return (Criteria) this;
        }

        public Criteria andChainIdIsNull() {
            addCriterion("chain_id is null");
            return (Criteria) this;
        }

        public Criteria andChainIdIsNotNull() {
            addCriterion("chain_id is not null");
            return (Criteria) this;
        }

        public Criteria andChainIdEqualTo(Integer value) {
            addCriterion("chain_id =", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdNotEqualTo(Integer value) {
            addCriterion("chain_id <>", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdGreaterThan(Integer value) {
            addCriterion("chain_id >", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("chain_id >=", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdLessThan(Integer value) {
            addCriterion("chain_id <", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdLessThanOrEqualTo(Integer value) {
            addCriterion("chain_id <=", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdIn(List<Integer> values) {
            addCriterion("chain_id in", values, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdNotIn(List<Integer> values) {
            addCriterion("chain_id not in", values, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdBetween(Integer value1, Integer value2) {
            addCriterion("chain_id between", value1, value2, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdNotBetween(Integer value1, Integer value2) {
            addCriterion("chain_id not between", value1, value2, "chainId");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameIsNull() {
            addCriterion("front_peer_name is null");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameIsNotNull() {
            addCriterion("front_peer_name is not null");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameEqualTo(String value) {
            addCriterion("front_peer_name =", value, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameNotEqualTo(String value) {
            addCriterion("front_peer_name <>", value, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameGreaterThan(String value) {
            addCriterion("front_peer_name >", value, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameGreaterThanOrEqualTo(String value) {
            addCriterion("front_peer_name >=", value, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameLessThan(String value) {
            addCriterion("front_peer_name <", value, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameLessThanOrEqualTo(String value) {
            addCriterion("front_peer_name <=", value, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameLike(String value) {
            addCriterion("front_peer_name like", value, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameNotLike(String value) {
            addCriterion("front_peer_name not like", value, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameIn(List<String> values) {
            addCriterion("front_peer_name in", values, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameNotIn(List<String> values) {
            addCriterion("front_peer_name not in", values, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameBetween(String value1, String value2) {
            addCriterion("front_peer_name between", value1, value2, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andFrontPeerNameNotBetween(String value1, String value2) {
            addCriterion("front_peer_name not between", value1, value2, "frontPeerName");
            return (Criteria) this;
        }

        public Criteria andNodeIdIsNull() {
            addCriterion("node_id is null");
            return (Criteria) this;
        }

        public Criteria andNodeIdIsNotNull() {
            addCriterion("node_id is not null");
            return (Criteria) this;
        }

        public Criteria andNodeIdEqualTo(String value) {
            addCriterion("node_id =", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdNotEqualTo(String value) {
            addCriterion("node_id <>", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdGreaterThan(String value) {
            addCriterion("node_id >", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdGreaterThanOrEqualTo(String value) {
            addCriterion("node_id >=", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdLessThan(String value) {
            addCriterion("node_id <", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdLessThanOrEqualTo(String value) {
            addCriterion("node_id <=", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdLike(String value) {
            addCriterion("node_id like", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdNotLike(String value) {
            addCriterion("node_id not like", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdIn(List<String> values) {
            addCriterion("node_id in", values, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdNotIn(List<String> values) {
            addCriterion("node_id not in", values, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdBetween(String value1, String value2) {
            addCriterion("node_id between", value1, value2, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdNotBetween(String value1, String value2) {
            addCriterion("node_id not between", value1, value2, "nodeId");
            return (Criteria) this;
        }

        public Criteria andFrontIpIsNull() {
            addCriterion("front_ip is null");
            return (Criteria) this;
        }

        public Criteria andFrontIpIsNotNull() {
            addCriterion("front_ip is not null");
            return (Criteria) this;
        }

        public Criteria andFrontIpEqualTo(String value) {
            addCriterion("front_ip =", value, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpNotEqualTo(String value) {
            addCriterion("front_ip <>", value, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpGreaterThan(String value) {
            addCriterion("front_ip >", value, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpGreaterThanOrEqualTo(String value) {
            addCriterion("front_ip >=", value, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpLessThan(String value) {
            addCriterion("front_ip <", value, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpLessThanOrEqualTo(String value) {
            addCriterion("front_ip <=", value, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpLike(String value) {
            addCriterion("front_ip like", value, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpNotLike(String value) {
            addCriterion("front_ip not like", value, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpIn(List<String> values) {
            addCriterion("front_ip in", values, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpNotIn(List<String> values) {
            addCriterion("front_ip not in", values, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpBetween(String value1, String value2) {
            addCriterion("front_ip between", value1, value2, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontIpNotBetween(String value1, String value2) {
            addCriterion("front_ip not between", value1, value2, "frontIp");
            return (Criteria) this;
        }

        public Criteria andFrontPortIsNull() {
            addCriterion("front_port is null");
            return (Criteria) this;
        }

        public Criteria andFrontPortIsNotNull() {
            addCriterion("front_port is not null");
            return (Criteria) this;
        }

        public Criteria andFrontPortEqualTo(Integer value) {
            addCriterion("front_port =", value, "frontPort");
            return (Criteria) this;
        }

        public Criteria andFrontPortNotEqualTo(Integer value) {
            addCriterion("front_port <>", value, "frontPort");
            return (Criteria) this;
        }

        public Criteria andFrontPortGreaterThan(Integer value) {
            addCriterion("front_port >", value, "frontPort");
            return (Criteria) this;
        }

        public Criteria andFrontPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("front_port >=", value, "frontPort");
            return (Criteria) this;
        }

        public Criteria andFrontPortLessThan(Integer value) {
            addCriterion("front_port <", value, "frontPort");
            return (Criteria) this;
        }

        public Criteria andFrontPortLessThanOrEqualTo(Integer value) {
            addCriterion("front_port <=", value, "frontPort");
            return (Criteria) this;
        }

        public Criteria andFrontPortIn(List<Integer> values) {
            addCriterion("front_port in", values, "frontPort");
            return (Criteria) this;
        }

        public Criteria andFrontPortNotIn(List<Integer> values) {
            addCriterion("front_port not in", values, "frontPort");
            return (Criteria) this;
        }

        public Criteria andFrontPortBetween(Integer value1, Integer value2) {
            addCriterion("front_port between", value1, value2, "frontPort");
            return (Criteria) this;
        }

        public Criteria andFrontPortNotBetween(Integer value1, Integer value2) {
            addCriterion("front_port not between", value1, value2, "frontPort");
            return (Criteria) this;
        }

        public Criteria andAgencyIsNull() {
            addCriterion("agency is null");
            return (Criteria) this;
        }

        public Criteria andAgencyIsNotNull() {
            addCriterion("agency is not null");
            return (Criteria) this;
        }

        public Criteria andAgencyEqualTo(String value) {
            addCriterion("agency =", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotEqualTo(String value) {
            addCriterion("agency <>", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyGreaterThan(String value) {
            addCriterion("agency >", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyGreaterThanOrEqualTo(String value) {
            addCriterion("agency >=", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyLessThan(String value) {
            addCriterion("agency <", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyLessThanOrEqualTo(String value) {
            addCriterion("agency <=", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyLike(String value) {
            addCriterion("agency like", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotLike(String value) {
            addCriterion("agency not like", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyIn(List<String> values) {
            addCriterion("agency in", values, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotIn(List<String> values) {
            addCriterion("agency not in", values, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyBetween(String value1, String value2) {
            addCriterion("agency between", value1, value2, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotBetween(String value1, String value2) {
            addCriterion("agency not between", value1, value2, "agency");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andFrontStatusIsNull() {
            addCriterion("front_status is null");
            return (Criteria) this;
        }

        public Criteria andFrontStatusIsNotNull() {
            addCriterion("front_status is not null");
            return (Criteria) this;
        }

        public Criteria andFrontStatusEqualTo(Integer value) {
            addCriterion("front_status =", value, "frontStatus");
            return (Criteria) this;
        }

        public Criteria andFrontStatusNotEqualTo(Integer value) {
            addCriterion("front_status <>", value, "frontStatus");
            return (Criteria) this;
        }

        public Criteria andFrontStatusGreaterThan(Integer value) {
            addCriterion("front_status >", value, "frontStatus");
            return (Criteria) this;
        }

        public Criteria andFrontStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("front_status >=", value, "frontStatus");
            return (Criteria) this;
        }

        public Criteria andFrontStatusLessThan(Integer value) {
            addCriterion("front_status <", value, "frontStatus");
            return (Criteria) this;
        }

        public Criteria andFrontStatusLessThanOrEqualTo(Integer value) {
            addCriterion("front_status <=", value, "frontStatus");
            return (Criteria) this;
        }

        public Criteria andFrontStatusIn(List<Integer> values) {
            addCriterion("front_status in", values, "frontStatus");
            return (Criteria) this;
        }

        public Criteria andFrontStatusNotIn(List<Integer> values) {
            addCriterion("front_status not in", values, "frontStatus");
            return (Criteria) this;
        }

        public Criteria andFrontStatusBetween(Integer value1, Integer value2) {
            addCriterion("front_status between", value1, value2, "frontStatus");
            return (Criteria) this;
        }

        public Criteria andFrontStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("front_status not between", value1, value2, "frontStatus");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andContainerNameIsNull() {
            addCriterion("container_name is null");
            return (Criteria) this;
        }

        public Criteria andContainerNameIsNotNull() {
            addCriterion("container_name is not null");
            return (Criteria) this;
        }

        public Criteria andContainerNameEqualTo(String value) {
            addCriterion("container_name =", value, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameNotEqualTo(String value) {
            addCriterion("container_name <>", value, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameGreaterThan(String value) {
            addCriterion("container_name >", value, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameGreaterThanOrEqualTo(String value) {
            addCriterion("container_name >=", value, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameLessThan(String value) {
            addCriterion("container_name <", value, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameLessThanOrEqualTo(String value) {
            addCriterion("container_name <=", value, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameLike(String value) {
            addCriterion("container_name like", value, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameNotLike(String value) {
            addCriterion("container_name not like", value, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameIn(List<String> values) {
            addCriterion("container_name in", values, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameNotIn(List<String> values) {
            addCriterion("container_name not in", values, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameBetween(String value1, String value2) {
            addCriterion("container_name between", value1, value2, "containerName");
            return (Criteria) this;
        }

        public Criteria andContainerNameNotBetween(String value1, String value2) {
            addCriterion("container_name not between", value1, value2, "containerName");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortIsNull() {
            addCriterion("jsonrpc_port is null");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortIsNotNull() {
            addCriterion("jsonrpc_port is not null");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortEqualTo(Integer value) {
            addCriterion("jsonrpc_port =", value, "jsonrpcPort");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortNotEqualTo(Integer value) {
            addCriterion("jsonrpc_port <>", value, "jsonrpcPort");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortGreaterThan(Integer value) {
            addCriterion("jsonrpc_port >", value, "jsonrpcPort");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("jsonrpc_port >=", value, "jsonrpcPort");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortLessThan(Integer value) {
            addCriterion("jsonrpc_port <", value, "jsonrpcPort");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortLessThanOrEqualTo(Integer value) {
            addCriterion("jsonrpc_port <=", value, "jsonrpcPort");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortIn(List<Integer> values) {
            addCriterion("jsonrpc_port in", values, "jsonrpcPort");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortNotIn(List<Integer> values) {
            addCriterion("jsonrpc_port not in", values, "jsonrpcPort");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortBetween(Integer value1, Integer value2) {
            addCriterion("jsonrpc_port between", value1, value2, "jsonrpcPort");
            return (Criteria) this;
        }

        public Criteria andJsonrpcPortNotBetween(Integer value1, Integer value2) {
            addCriterion("jsonrpc_port not between", value1, value2, "jsonrpcPort");
            return (Criteria) this;
        }

        public Criteria andP2pPortIsNull() {
            addCriterion("p2p_port is null");
            return (Criteria) this;
        }

        public Criteria andP2pPortIsNotNull() {
            addCriterion("p2p_port is not null");
            return (Criteria) this;
        }

        public Criteria andP2pPortEqualTo(Integer value) {
            addCriterion("p2p_port =", value, "p2pPort");
            return (Criteria) this;
        }

        public Criteria andP2pPortNotEqualTo(Integer value) {
            addCriterion("p2p_port <>", value, "p2pPort");
            return (Criteria) this;
        }

        public Criteria andP2pPortGreaterThan(Integer value) {
            addCriterion("p2p_port >", value, "p2pPort");
            return (Criteria) this;
        }

        public Criteria andP2pPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("p2p_port >=", value, "p2pPort");
            return (Criteria) this;
        }

        public Criteria andP2pPortLessThan(Integer value) {
            addCriterion("p2p_port <", value, "p2pPort");
            return (Criteria) this;
        }

        public Criteria andP2pPortLessThanOrEqualTo(Integer value) {
            addCriterion("p2p_port <=", value, "p2pPort");
            return (Criteria) this;
        }

        public Criteria andP2pPortIn(List<Integer> values) {
            addCriterion("p2p_port in", values, "p2pPort");
            return (Criteria) this;
        }

        public Criteria andP2pPortNotIn(List<Integer> values) {
            addCriterion("p2p_port not in", values, "p2pPort");
            return (Criteria) this;
        }

        public Criteria andP2pPortBetween(Integer value1, Integer value2) {
            addCriterion("p2p_port between", value1, value2, "p2pPort");
            return (Criteria) this;
        }

        public Criteria andP2pPortNotBetween(Integer value1, Integer value2) {
            addCriterion("p2p_port not between", value1, value2, "p2pPort");
            return (Criteria) this;
        }

        public Criteria andChannelPortIsNull() {
            addCriterion("channel_port is null");
            return (Criteria) this;
        }

        public Criteria andChannelPortIsNotNull() {
            addCriterion("channel_port is not null");
            return (Criteria) this;
        }

        public Criteria andChannelPortEqualTo(Integer value) {
            addCriterion("channel_port =", value, "channelPort");
            return (Criteria) this;
        }

        public Criteria andChannelPortNotEqualTo(Integer value) {
            addCriterion("channel_port <>", value, "channelPort");
            return (Criteria) this;
        }

        public Criteria andChannelPortGreaterThan(Integer value) {
            addCriterion("channel_port >", value, "channelPort");
            return (Criteria) this;
        }

        public Criteria andChannelPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_port >=", value, "channelPort");
            return (Criteria) this;
        }

        public Criteria andChannelPortLessThan(Integer value) {
            addCriterion("channel_port <", value, "channelPort");
            return (Criteria) this;
        }

        public Criteria andChannelPortLessThanOrEqualTo(Integer value) {
            addCriterion("channel_port <=", value, "channelPort");
            return (Criteria) this;
        }

        public Criteria andChannelPortIn(List<Integer> values) {
            addCriterion("channel_port in", values, "channelPort");
            return (Criteria) this;
        }

        public Criteria andChannelPortNotIn(List<Integer> values) {
            addCriterion("channel_port not in", values, "channelPort");
            return (Criteria) this;
        }

        public Criteria andChannelPortBetween(Integer value1, Integer value2) {
            addCriterion("channel_port between", value1, value2, "channelPort");
            return (Criteria) this;
        }

        public Criteria andChannelPortNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_port not between", value1, value2, "channelPort");
            return (Criteria) this;
        }

        public Criteria andChainNameIsNull() {
            addCriterion("chain_name is null");
            return (Criteria) this;
        }

        public Criteria andChainNameIsNotNull() {
            addCriterion("chain_name is not null");
            return (Criteria) this;
        }

        public Criteria andChainNameEqualTo(String value) {
            addCriterion("chain_name =", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameNotEqualTo(String value) {
            addCriterion("chain_name <>", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameGreaterThan(String value) {
            addCriterion("chain_name >", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameGreaterThanOrEqualTo(String value) {
            addCriterion("chain_name >=", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameLessThan(String value) {
            addCriterion("chain_name <", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameLessThanOrEqualTo(String value) {
            addCriterion("chain_name <=", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameLike(String value) {
            addCriterion("chain_name like", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameNotLike(String value) {
            addCriterion("chain_name not like", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameIn(List<String> values) {
            addCriterion("chain_name in", values, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameNotIn(List<String> values) {
            addCriterion("chain_name not in", values, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameBetween(String value1, String value2) {
            addCriterion("chain_name between", value1, value2, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameNotBetween(String value1, String value2) {
            addCriterion("chain_name not between", value1, value2, "chainName");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdIsNull() {
            addCriterion("ext_company_id is null");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdIsNotNull() {
            addCriterion("ext_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdEqualTo(Integer value) {
            addCriterion("ext_company_id =", value, "extCompanyId");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdNotEqualTo(Integer value) {
            addCriterion("ext_company_id <>", value, "extCompanyId");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdGreaterThan(Integer value) {
            addCriterion("ext_company_id >", value, "extCompanyId");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ext_company_id >=", value, "extCompanyId");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdLessThan(Integer value) {
            addCriterion("ext_company_id <", value, "extCompanyId");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("ext_company_id <=", value, "extCompanyId");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdIn(List<Integer> values) {
            addCriterion("ext_company_id in", values, "extCompanyId");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdNotIn(List<Integer> values) {
            addCriterion("ext_company_id not in", values, "extCompanyId");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("ext_company_id between", value1, value2, "extCompanyId");
            return (Criteria) this;
        }

        public Criteria andExtCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ext_company_id not between", value1, value2, "extCompanyId");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdIsNull() {
            addCriterion("ext_agency_id is null");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdIsNotNull() {
            addCriterion("ext_agency_id is not null");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdEqualTo(Integer value) {
            addCriterion("ext_agency_id =", value, "extAgencyId");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdNotEqualTo(Integer value) {
            addCriterion("ext_agency_id <>", value, "extAgencyId");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdGreaterThan(Integer value) {
            addCriterion("ext_agency_id >", value, "extAgencyId");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ext_agency_id >=", value, "extAgencyId");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdLessThan(Integer value) {
            addCriterion("ext_agency_id <", value, "extAgencyId");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdLessThanOrEqualTo(Integer value) {
            addCriterion("ext_agency_id <=", value, "extAgencyId");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdIn(List<Integer> values) {
            addCriterion("ext_agency_id in", values, "extAgencyId");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdNotIn(List<Integer> values) {
            addCriterion("ext_agency_id not in", values, "extAgencyId");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdBetween(Integer value1, Integer value2) {
            addCriterion("ext_agency_id between", value1, value2, "extAgencyId");
            return (Criteria) this;
        }

        public Criteria andExtAgencyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ext_agency_id not between", value1, value2, "extAgencyId");
            return (Criteria) this;
        }

        public Criteria andExtHostIdIsNull() {
            addCriterion("ext_host_id is null");
            return (Criteria) this;
        }

        public Criteria andExtHostIdIsNotNull() {
            addCriterion("ext_host_id is not null");
            return (Criteria) this;
        }

        public Criteria andExtHostIdEqualTo(Integer value) {
            addCriterion("ext_host_id =", value, "extHostId");
            return (Criteria) this;
        }

        public Criteria andExtHostIdNotEqualTo(Integer value) {
            addCriterion("ext_host_id <>", value, "extHostId");
            return (Criteria) this;
        }

        public Criteria andExtHostIdGreaterThan(Integer value) {
            addCriterion("ext_host_id >", value, "extHostId");
            return (Criteria) this;
        }

        public Criteria andExtHostIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ext_host_id >=", value, "extHostId");
            return (Criteria) this;
        }

        public Criteria andExtHostIdLessThan(Integer value) {
            addCriterion("ext_host_id <", value, "extHostId");
            return (Criteria) this;
        }

        public Criteria andExtHostIdLessThanOrEqualTo(Integer value) {
            addCriterion("ext_host_id <=", value, "extHostId");
            return (Criteria) this;
        }

        public Criteria andExtHostIdIn(List<Integer> values) {
            addCriterion("ext_host_id in", values, "extHostId");
            return (Criteria) this;
        }

        public Criteria andExtHostIdNotIn(List<Integer> values) {
            addCriterion("ext_host_id not in", values, "extHostId");
            return (Criteria) this;
        }

        public Criteria andExtHostIdBetween(Integer value1, Integer value2) {
            addCriterion("ext_host_id between", value1, value2, "extHostId");
            return (Criteria) this;
        }

        public Criteria andExtHostIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ext_host_id not between", value1, value2, "extHostId");
            return (Criteria) this;
        }

        public Criteria andHostIndexIsNull() {
            addCriterion("host_index is null");
            return (Criteria) this;
        }

        public Criteria andHostIndexIsNotNull() {
            addCriterion("host_index is not null");
            return (Criteria) this;
        }

        public Criteria andHostIndexEqualTo(Integer value) {
            addCriterion("host_index =", value, "hostIndex");
            return (Criteria) this;
        }

        public Criteria andHostIndexNotEqualTo(Integer value) {
            addCriterion("host_index <>", value, "hostIndex");
            return (Criteria) this;
        }

        public Criteria andHostIndexGreaterThan(Integer value) {
            addCriterion("host_index >", value, "hostIndex");
            return (Criteria) this;
        }

        public Criteria andHostIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("host_index >=", value, "hostIndex");
            return (Criteria) this;
        }

        public Criteria andHostIndexLessThan(Integer value) {
            addCriterion("host_index <", value, "hostIndex");
            return (Criteria) this;
        }

        public Criteria andHostIndexLessThanOrEqualTo(Integer value) {
            addCriterion("host_index <=", value, "hostIndex");
            return (Criteria) this;
        }

        public Criteria andHostIndexIn(List<Integer> values) {
            addCriterion("host_index in", values, "hostIndex");
            return (Criteria) this;
        }

        public Criteria andHostIndexNotIn(List<Integer> values) {
            addCriterion("host_index not in", values, "hostIndex");
            return (Criteria) this;
        }

        public Criteria andHostIndexBetween(Integer value1, Integer value2) {
            addCriterion("host_index between", value1, value2, "hostIndex");
            return (Criteria) this;
        }

        public Criteria andHostIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("host_index not between", value1, value2, "hostIndex");
            return (Criteria) this;
        }

        public Criteria andSshUserIsNull() {
            addCriterion("ssh_user is null");
            return (Criteria) this;
        }

        public Criteria andSshUserIsNotNull() {
            addCriterion("ssh_user is not null");
            return (Criteria) this;
        }

        public Criteria andSshUserEqualTo(String value) {
            addCriterion("ssh_user =", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserNotEqualTo(String value) {
            addCriterion("ssh_user <>", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserGreaterThan(String value) {
            addCriterion("ssh_user >", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserGreaterThanOrEqualTo(String value) {
            addCriterion("ssh_user >=", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserLessThan(String value) {
            addCriterion("ssh_user <", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserLessThanOrEqualTo(String value) {
            addCriterion("ssh_user <=", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserLike(String value) {
            addCriterion("ssh_user like", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserNotLike(String value) {
            addCriterion("ssh_user not like", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserIn(List<String> values) {
            addCriterion("ssh_user in", values, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserNotIn(List<String> values) {
            addCriterion("ssh_user not in", values, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserBetween(String value1, String value2) {
            addCriterion("ssh_user between", value1, value2, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserNotBetween(String value1, String value2) {
            addCriterion("ssh_user not between", value1, value2, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshPortIsNull() {
            addCriterion("ssh_port is null");
            return (Criteria) this;
        }

        public Criteria andSshPortIsNotNull() {
            addCriterion("ssh_port is not null");
            return (Criteria) this;
        }

        public Criteria andSshPortEqualTo(Integer value) {
            addCriterion("ssh_port =", value, "sshPort");
            return (Criteria) this;
        }

        public Criteria andSshPortNotEqualTo(Integer value) {
            addCriterion("ssh_port <>", value, "sshPort");
            return (Criteria) this;
        }

        public Criteria andSshPortGreaterThan(Integer value) {
            addCriterion("ssh_port >", value, "sshPort");
            return (Criteria) this;
        }

        public Criteria andSshPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("ssh_port >=", value, "sshPort");
            return (Criteria) this;
        }

        public Criteria andSshPortLessThan(Integer value) {
            addCriterion("ssh_port <", value, "sshPort");
            return (Criteria) this;
        }

        public Criteria andSshPortLessThanOrEqualTo(Integer value) {
            addCriterion("ssh_port <=", value, "sshPort");
            return (Criteria) this;
        }

        public Criteria andSshPortIn(List<Integer> values) {
            addCriterion("ssh_port in", values, "sshPort");
            return (Criteria) this;
        }

        public Criteria andSshPortNotIn(List<Integer> values) {
            addCriterion("ssh_port not in", values, "sshPort");
            return (Criteria) this;
        }

        public Criteria andSshPortBetween(Integer value1, Integer value2) {
            addCriterion("ssh_port between", value1, value2, "sshPort");
            return (Criteria) this;
        }

        public Criteria andSshPortNotBetween(Integer value1, Integer value2) {
            addCriterion("ssh_port not between", value1, value2, "sshPort");
            return (Criteria) this;
        }

        public Criteria andDockerPortIsNull() {
            addCriterion("docker_port is null");
            return (Criteria) this;
        }

        public Criteria andDockerPortIsNotNull() {
            addCriterion("docker_port is not null");
            return (Criteria) this;
        }

        public Criteria andDockerPortEqualTo(Integer value) {
            addCriterion("docker_port =", value, "dockerPort");
            return (Criteria) this;
        }

        public Criteria andDockerPortNotEqualTo(Integer value) {
            addCriterion("docker_port <>", value, "dockerPort");
            return (Criteria) this;
        }

        public Criteria andDockerPortGreaterThan(Integer value) {
            addCriterion("docker_port >", value, "dockerPort");
            return (Criteria) this;
        }

        public Criteria andDockerPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("docker_port >=", value, "dockerPort");
            return (Criteria) this;
        }

        public Criteria andDockerPortLessThan(Integer value) {
            addCriterion("docker_port <", value, "dockerPort");
            return (Criteria) this;
        }

        public Criteria andDockerPortLessThanOrEqualTo(Integer value) {
            addCriterion("docker_port <=", value, "dockerPort");
            return (Criteria) this;
        }

        public Criteria andDockerPortIn(List<Integer> values) {
            addCriterion("docker_port in", values, "dockerPort");
            return (Criteria) this;
        }

        public Criteria andDockerPortNotIn(List<Integer> values) {
            addCriterion("docker_port not in", values, "dockerPort");
            return (Criteria) this;
        }

        public Criteria andDockerPortBetween(Integer value1, Integer value2) {
            addCriterion("docker_port between", value1, value2, "dockerPort");
            return (Criteria) this;
        }

        public Criteria andDockerPortNotBetween(Integer value1, Integer value2) {
            addCriterion("docker_port not between", value1, value2, "dockerPort");
            return (Criteria) this;
        }

        public Criteria andRootOnHostIsNull() {
            addCriterion("root_on_host is null");
            return (Criteria) this;
        }

        public Criteria andRootOnHostIsNotNull() {
            addCriterion("root_on_host is not null");
            return (Criteria) this;
        }

        public Criteria andRootOnHostEqualTo(String value) {
            addCriterion("root_on_host =", value, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostNotEqualTo(String value) {
            addCriterion("root_on_host <>", value, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostGreaterThan(String value) {
            addCriterion("root_on_host >", value, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostGreaterThanOrEqualTo(String value) {
            addCriterion("root_on_host >=", value, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostLessThan(String value) {
            addCriterion("root_on_host <", value, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostLessThanOrEqualTo(String value) {
            addCriterion("root_on_host <=", value, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostLike(String value) {
            addCriterion("root_on_host like", value, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostNotLike(String value) {
            addCriterion("root_on_host not like", value, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostIn(List<String> values) {
            addCriterion("root_on_host in", values, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostNotIn(List<String> values) {
            addCriterion("root_on_host not in", values, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostBetween(String value1, String value2) {
            addCriterion("root_on_host between", value1, value2, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andRootOnHostNotBetween(String value1, String value2) {
            addCriterion("root_on_host not between", value1, value2, "rootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostIsNull() {
            addCriterion("node_root_on_host is null");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostIsNotNull() {
            addCriterion("node_root_on_host is not null");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostEqualTo(String value) {
            addCriterion("node_root_on_host =", value, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostNotEqualTo(String value) {
            addCriterion("node_root_on_host <>", value, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostGreaterThan(String value) {
            addCriterion("node_root_on_host >", value, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostGreaterThanOrEqualTo(String value) {
            addCriterion("node_root_on_host >=", value, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostLessThan(String value) {
            addCriterion("node_root_on_host <", value, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostLessThanOrEqualTo(String value) {
            addCriterion("node_root_on_host <=", value, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostLike(String value) {
            addCriterion("node_root_on_host like", value, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostNotLike(String value) {
            addCriterion("node_root_on_host not like", value, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostIn(List<String> values) {
            addCriterion("node_root_on_host in", values, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostNotIn(List<String> values) {
            addCriterion("node_root_on_host not in", values, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostBetween(String value1, String value2) {
            addCriterion("node_root_on_host between", value1, value2, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andNodeRootOnHostNotBetween(String value1, String value2) {
            addCriterion("node_root_on_host not between", value1, value2, "nodeRootOnHost");
            return (Criteria) this;
        }

        public Criteria andFrontTypeIsNull() {
            addCriterion("front_type is null");
            return (Criteria) this;
        }

        public Criteria andFrontTypeIsNotNull() {
            addCriterion("front_type is not null");
            return (Criteria) this;
        }

        public Criteria andFrontTypeEqualTo(Integer value) {
            addCriterion("front_type =", value, "frontType");
            return (Criteria) this;
        }

        public Criteria andFrontTypeNotEqualTo(Integer value) {
            addCriterion("front_type <>", value, "frontType");
            return (Criteria) this;
        }

        public Criteria andFrontTypeGreaterThan(Integer value) {
            addCriterion("front_type >", value, "frontType");
            return (Criteria) this;
        }

        public Criteria andFrontTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("front_type >=", value, "frontType");
            return (Criteria) this;
        }

        public Criteria andFrontTypeLessThan(Integer value) {
            addCriterion("front_type <", value, "frontType");
            return (Criteria) this;
        }

        public Criteria andFrontTypeLessThanOrEqualTo(Integer value) {
            addCriterion("front_type <=", value, "frontType");
            return (Criteria) this;
        }

        public Criteria andFrontTypeIn(List<Integer> values) {
            addCriterion("front_type in", values, "frontType");
            return (Criteria) this;
        }

        public Criteria andFrontTypeNotIn(List<Integer> values) {
            addCriterion("front_type not in", values, "frontType");
            return (Criteria) this;
        }

        public Criteria andFrontTypeBetween(Integer value1, Integer value2) {
            addCriterion("front_type between", value1, value2, "frontType");
            return (Criteria) this;
        }

        public Criteria andFrontTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("front_type not between", value1, value2, "frontType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_front
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
