package com.webank.webase.chain.mgr.repository.bean;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class TbFront implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_front.front_id
     *
     * @mbg.generated
     */
    private Integer frontId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_front.chain_id
     *
     * @mbg.generated
     */
    private Integer chainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_front.node_id
     *
     * @mbg.generated
     */
    private String nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_front.front_ip
     *
     * @mbg.generated
     */
    private String frontIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_front.front_port
     *
     * @mbg.generated
     */
    private Integer frontPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_front.agency
     *
     * @mbg.generated
     */
    private String agency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_front.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_front.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_front.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_front
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
