package com.webank.webase.chain.mgr.repository.bean;

import java.io.Serializable;
import java.util.Date;

import com.webank.webase.chain.mgr.base.enums.HostStatusEnum;
import com.webank.webase.chain.mgr.deploy.req.ReqHostCheckAndInit;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class TbHost implements Serializable {

    public static TbHost init(int extAgencyId, String extAgencyName, ReqHostCheckAndInit.Host host, HostStatusEnum hostStatusEnum ){
        Date now = new Date();
        TbHost tbHost = new TbHost();
        tbHost.setExtAgencyId(extAgencyId);
        tbHost.setExtAgencyName(extAgencyName);
        tbHost.setIp(host.getIp());
        tbHost.setSshUser(host.getSshUser());
        tbHost.setSshPort(host.getSshPort());
        tbHost.setRootDir(host.getRootDir());
        tbHost.setDockerPort(host.getDockerDemonPort());
        tbHost.setHostStatus(hostStatusEnum.getId());
        tbHost.setCreateTime(now);
        tbHost.setModifyTime(now);

        return tbHost;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.ext_agency_id
     *
     * @mbg.generated
     */
    private Integer extAgencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.ext_agency_name
     *
     * @mbg.generated
     */
    private String extAgencyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.ssh_user
     *
     * @mbg.generated
     */
    private String sshUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.ssh_port
     *
     * @mbg.generated
     */
    private Integer sshPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.root_dir
     *
     * @mbg.generated
     */
    private String rootDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.docker_port
     *
     * @mbg.generated
     */
    private Integer dockerPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.host_status
     *
     * @mbg.generated
     */
    private Byte hostStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_host.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_host
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
