#server config
server:
  port: 5005
  servlet:
    context-path: /WeBASE-Chain-Manager


#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.webank.webase.chain.mgr.repository.bean
  mapperLocations: classpath:mapper/*.xml



# database connection configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${WEBASE_DB_IP:127.0.0.1}:${WEBASE_DB_PORT:3306}/webasechainmanager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ${WEBASE_DB_UNAME:defaultAccount}
    password: ${WEBASE_DB_PWD:defaultPassword}

#log config
logging:
  config: classpath:log/log4j2.xml
  level:
    com.webank.webase.chain.mgr: info

#constants
constant:
  ###common
  resetGroupListCycle: 300000
  groupInvalidGrayscaleValue: 1M    # y:year, M:month, d:day of month, h:hour, m:minute, n:forever valid

  ###front http request
  frontUrl: http://%1s:%2d/WeBASE-Front/%3s
  httpTimeOut: 5000
  contractDeployTimeOut: 30000
  maxRequestFail: 3
  sleepWhenHttpMaxFail: 60000

  ### change node type
  maxBlockDifferenceOfNewSealer: 3  # The maximum allowable block difference of the new consensus node
  addSealerNodeCycle: 30000

  #### data related config
  # if pull data(can change by interface)
  ifPullData: true
  ## data pull
  startBlockNumber: 0
  crawlBatchUnit: 50
  dataPullCron: 0/10 * * * * ?
  ## if multiLiving
  multiLiving: false
  ## group
  refreshSubTableTaskFixedDelay: 5000
  ## delete retain max block and trans data
  isDeleteInfo: true
  deleteInfoCron: "0 0/1 * * * ?"
  blockRetainMax: 5000
  transRetainMax: 10000
  ## stat txn daily
  statTxnDailyTaskFixedDelay: 60000

  ## 部署配置
  dockerRepository: fiscoorg/fisco-webase
  dockerRestartPeriodTime: 30000
  webaseSignAddress: ${WEBASE_SIGN:127.0.0.1:5004}

# executor config
executor:
  corePoolSize: 10
  maxPoolSize: 30
  queueSize: 50
  threadNamePrefix: "chain-mgr-async-"
