#server config
server:
  port: 5005
  servlet:
    context-path: /WeBASE-Chain-Manager


#mybatis config
mybatis:
  typeAliasesPackage: com.webank.webase.chain.mgr
  mapperLocations: classpath:mapper/*.xml


# database connection configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/webasechainmanager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: "defaultAccount"
    password: "defaultPassword"

#log config
logging:
  config: classpath:log/log4j2-dev.xml
  level:
    com.webank.webase.chain.mgr: info

#constants
constant:
  ###common
  resetGroupListCycle: 600000
  groupInvalidGrayscaleValue: 1M    # y:year, M:month, d:day of month, h:hour, m:minute, n:forever valid

  ###front http request
  frontUrl: http://%1s:%2d/WeBASE-Front/%3s
  httpTimeOut: 5000
  contractDeployTimeOut: 30000
  isPrivateKeyEncrypt: true
  maxRequestFail: 3
  sleepWhenHttpMaxFail: 60000

# executor config
executor:
  corePoolSize: 3
  maxPoolSize: 10
  queueSize: 50
  threadNamePrefix: "chain-mgr-async-"
