package com.webank.webase.chain.mgr.repository.mapper;

import com.webank.webase.chain.mgr.repository.bean.TbAgency;
import org.apache.ibatis.jdbc.SQL;

public class TbAgencySqlProvider {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_agency
     *
     * @mbg.generated
     */
    public static final String ALL_COLUMN_FIELDS = "id,agency_name,agency_desc,create_time,modify_time";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agency
     *
     * @mbg.generated
     */
    public String insertSelective(TbAgency record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_agency");
        if (record.getAgencyName() != null) {
            sql.VALUES("agency_name", "#{agencyName,jdbcType=VARCHAR}");
        }
        if (record.getAgencyDesc() != null) {
            sql.VALUES("agency_desc", "#{agencyDesc,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getModifyTime() != null) {
            sql.VALUES("modify_time", "#{modifyTime,jdbcType=TIMESTAMP}");
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agency
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TbAgency record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_agency");
        if (record.getAgencyName() != null) {
            sql.SET("agency_name = #{agencyName,jdbcType=VARCHAR}");
        }
        if (record.getAgencyDesc() != null) {
            sql.SET("agency_desc = #{agencyDesc,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getModifyTime() != null) {
            sql.SET("modify_time = #{modifyTime,jdbcType=TIMESTAMP}");
        }
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        return sql.toString();
    }
}
